version: '3'
services:
  node-app:
    build: 
      context: .
      args: 
        NODE_ENV: development
    volumes:
  # ro represents the read only acceses to the node-app to the actual source code
      - ./:/app:ro
    environment:
      - NODE_ENV= development
      # this how you will override the default CMD in Dockerfile in docker-compose
    command: npm run dev