# this is common docker compose for both the dev and production docker image/container
version: '3'
services:
  node-app:
    build: .
    ports:
      - 3000:3000
    environment:
      - PORT=3000
  mongo-db:
    image: mongo
    env_file:
      - db.env