version: '3'
services:
  nginx:
      ports:
        - "80:80"
  node-app:
    deploy:
      replicas: 8
      restart-policy:
        condition: any
      update-config:
        parralelism: 2
        delay: 12s
    build: 
      context: .
      args: 
        NODE_ENV: production
    environment:
      - NODE_ENV= production
    command: node app.js