# this is common docker compose for both the dev and production docker image/container
version: '3'
services:
  node-app:
    build: .
    ports:
      - 3000:3000
    environment:
      - PORT=3000
  mongo-db:
    image: mongo
    env_file:
      - db.env
    volumes:
      - mongo-db:/data/db  




#You always have to mention all your named Volumes in the bottom Volumes sections so that the other services can access the named volume
volumes:
  mongo-db: