# this is common docker compose for both the dev and production docker image/container
version: '3'
services:
  node-app:
    build: .
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      # so the node app is depended on the mongo container to establish the database connection 
      # we launch the mongo container first and then the node container
    depends_on:
      - mongo-db  


  mongo-db:
    image: mongo
    env_file:
      - db.env
    volumes:
      - mongo-db:/data/db  

  redis:
    image: redis
    




#You always have to mention all your named Volumes in the bottom Volumes sections so that the other services can access the named volume
volumes:
  mongo-db: